swagger: "2.0"
info:
  title: Transactions API
  description: API endpoints for managing transactions
  version: "1.0.0"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transactions
      summary: Get all transactions for the current month, grouped by account
      description: Returns a list of transactions for the current month
      produces:
        - application/json
      responses:
        "200":
          description: A list of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "500":
          description: Internal Server Error
    post:
      tags:
        - Transactions
      summary: Create a new transaction
      description: Adds a new transaction to an account
      parameters:
        - in: body
          name: transaction
          description: Transaction to add
          required: true
          schema:
            $ref: "#/definitions/NewTransaction"
      produces:
        - application/json
      responses:
        "201":
          description: Transaction created
        "400":
          description: Invalid transaction data
        "500":
          description: Internal Server Error
  /transactions/{id}:
    get:
      tags:
        - Transactions
      summary: Get a specific transaction's details
      description: Returns details for a single transaction
      parameters:
        - in: path
          name: id
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      tags:
        - Transactions
      summary: Update a transaction
      description: Modifies details of an existing transaction
      parameters:
        - in: path
          name: id
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: transaction
          description: Updated transaction details
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Transaction updated
        "400":
          description: Invalid transaction data
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Transactions
      summary: Delete a transaction
      description: Removes a transaction from the account
      parameters:
        - in: path
          name: id
          description: ID of the transaction to delete
          required: true
          type: string
      responses:
        "204":
          description: Transaction deleted
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      date:
        type: string
        format: date
      amount:
        type: number
        format: double
      description:
        type: string
  NewTransaction:
    type: object
    properties:
      accountId:
        type: string
      date:
        type: string
        format: date
      amount:
        type: number
        format: double
      description:
        type: string
